### ISSUE TITLE
Sources

### ISSUE THREAD

**Issue by piwats** [piccolo-dev/android_kernel_bq_piccolo#1]
How about using the "vanilla" msm sources? or even vanilla?

https://www.codeaurora.org/cgit/quic/la/kernel/msm/

The bq sources should provide the device tree for the m5.

That way it would be possible to be independent from bq if it comes to the kernel.

**Comment by Kra1o5** [comment]
We are using CAF based kernel.

**Comment by piwats** [comment]
CAF = code aurora forum, if I'm correct. That is the first link.

Do you use the sources from them (CAF, e.g. msm) directly, or do you stick only to those released by bq?

**Comment by eloimuns** [comment]
The base of kernel sources is CAF.

Later, it've BQ changes (drivers and compatibility).

**Comment by Kra1o5** [comment]
You can see in what branch of CAF our kernel is based: https://github.com/piccolo-dev/android_kernel_bq_piccolo/tree/LA.BR.1.1.3-05610-8x16.0

**Comment by piwats** [comment]
That is very good. I was a bit confused. Thanks for the information. :)

**Comment by Kra1o5** [comment]
All is clear now, so i can close it.
