### ISSUE TITLE
nf: IDLETIMER: Adds the uid field in the msg

### ISSUE THREAD

**Issue by stucki** [piccolo-dev/android_kernel_bq_piccolo#3]
I stumbled over some warnings in the log and found this change:
http://review.cyanogenmod.org/#/q/I18fc73eada512e370d7ab24fc9f890845037b729

I think it should be merged into our kernel, too.

**Comment by stucki** [comment]
The error message in logcat was: `NetlinkEvent::FindParam(): Parameter 'UID' not found`

**Comment by Kra1o5** [comment]
Thanks, Now merged into our repo.

**Comment by stucki** [comment]
Thank you!
